

export default function Header({textoHeader}) {
    return(
    <header>{textoHeader} <br />Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut posuere nisl. Aenean consectetur nunc a rhoncus gravida. Aenean nec blandit felis. Nam venenatis pellentesque tortor, nec blandit lectus lacinia a. Pellentesque in viverra nisl. Nullam vestibulum est eget risus aliquet dictum. Cras non nulla sit amet massa rhoncus sodales. Etiam ullamcorper, augue nec laoreet scelerisque, ipsum odio porttitor diam, vel rhoncus nunc leo in libero. Aliquam erat volutpat. Ut suscipit vestibulum consectetur. Aliquam fermentum nibh eu arcu suscipit, a viverra eros accumsan. Vestibulum eget lacus pellentesque, laoreet ante eget, tincidunt ante. Nunc neque ante, volutpat in lorem luctus, finibus lobortis lacus. Nulla congue blandit iaculis.

        Maecenas elementum aliquam orci at bibendum. Nunc et sem convallis, tristique ipsum eu, tincidunt leo. Quisque ac accumsan diam. Etiam in interdum augue. Sed sodales consequat erat at euismod. Suspendisse pellentesque tellus vehicula mauris sollicitudin fringilla. Donec sagittis lobortis dapibus. Mauris a magna at diam congue tempor. In hac habitasse platea dictumst. Morbi sed erat risus. Maecenas id convallis lacus. Vivamus feugiat ipsum velit, sit amet elementum odio suscipit non. Donec luctus, augue vitae pharetra laoreet, diam libero lacinia enim, non auctor neque ipsum a mi. Duis maximus dolor in risus hendrerit, et cursus elit sagittis. Aenean ut urna nulla. Ut ut commodo sem, nec ullamcorper erat.

        Nullam sed tincidunt libero, et tincidunt risus. Suspendisse sit amet ante ullamcorper, ultrices orci id, rhoncus mi. Phasellus consectetur nisl in ligula dictum, a sodales sem elementum. Pellentesque vestibulum purus est, ac mollis ante vulputate non. Vivamus ac lobortis purus. Aliquam placerat tempor odio, in ornare sem elementum in. Aliquam id tortor faucibus, dapibus dolor eu, varius ante. Pellentesque arcu velit, sodales quis semper a, faucibus sed arcu. Integer sit amet ex vel lectus blandit bibendum non accumsan ex. Pellentesque lobortis, augue et venenatis suscipit, mi massa elementum leo, in rutrum velit est id ligula. Phasellus mattis massa in ex consequat, ut iaculis ligula mollis. Nulla id nisi in eros auctor maximus. Sed maximus congue consectetur. Etiam porttitor, nisi ac aliquam rhoncus, ante erat imperdiet dui, id fermentum mi turpis ac velit.</header>
    )
}